### ISSUE TITLE
Bug: Segmentation fault is caused when I click on aboutTextEditor.website

### ISSUE THREAD

**Issue by RafaelJohn9** [ubuntu/gnome-text-editor#24] opened 2024-05-20 19:18 UTC
[ubuntu.webm](https://github.com/ubuntu/gnome-text-editor/assets/125447154/6fb41ef0-ca63-4bd1-a390-bdf2a67d5e57)

**Comment by sergio-costas** [comment] 2024-05-22 09:02
In my case it doesn't crash, but shows two GLib/GObject errors. This looks like an upstream bug.

![imagen](https://github.com/ubuntu/gnome-text-editor/assets/105285003/a069217d-824e-4550-940b-9a13be7c4cd6)

**Comment by sergio-costas** [comment] 2024-05-22 09:21
In fact, checking the source code, it just calls adw_show_about_window(), so the bug seems to be in Adwaita library...

![imagen](https://github.com/ubuntu/gnome-text-editor/assets/105285003/e8a653cd-4cc2-48d7-a6ff-d7b0ab000364)

**Comment by RafaelJohn9** [comment] 2024-05-23 04:41
hmmm....interesting, have you tried locating the problem in the adawaita lib for easier debugging  or should I just report this an issue in their github repo

**Comment by sergio-costas** [comment] 2024-05-23 08:54
I'll try to find the bug in libadwaita, just in case it has already been fixed in upstream.

**Comment by sergio-costas** [comment] 2024-05-23 08:55
(the problem is that the day has only 24 hours 😅)

**Comment by RafaelJohn9** [comment] 2024-05-23 11:54
I'll try to debug too 😅😅, if that makes you feel better

**Comment by sergio-costas** [comment] 2024-05-23 15:42
I think that it has already been fixed upstream. Compare the link launcher in version 1.4 and in main:

![imagen](https://github.com/ubuntu/gnome-text-editor/assets/105285003/501865c5-5651-4215-9cc7-6b3337c18b5f)

![imagen](https://github.com/ubuntu/gnome-text-editor/assets/105285003/ab6159f1-18e0-4696-af0d-22d6d9a91e23)

**Comment by RafaelJohn9** [comment] 2024-05-23 17:44
yea true, it has been fixed🤝🤝..
So they were reading our conversation the whole time and they couldn't say hi 👋

**Comment by RafaelJohn9** [comment] 2024-05-23 17:44
anyway @sergio-costas  thanks

**Closed as completed** 2024-05-24 18:10 UTC

**Comment by RafaelJohn9** [comment] 2024-05-24 18:11
Issue Fixed
